// todo-app/src/components/AddTodo.vue
<script setup lang="ts">
import { ref } from "vue";

const userInput = ref("");

const emits = defineEmits<{ (e: "addtodo", text: string): void }>();

const handleSubmit = () => {
  emits("addtodo", userInput.value);

  userInput.value = "";
};
</script>

<template>
  <form @submit.prevent="handleSubmit">
    <input type="text" v-model="userInput" />
    <button>Spara</button>
  </form>
</template>

<style scoped></style>

// react-todo/src/components/AddTodo.tsx
import { ChangeEvent, FormEvent, useState } from "react";

interface IAddTodoProps {
  createTodo: (textFromUser: string) => void;
}

export const AddTodo = ({ createTodo }: IAddTodoProps) => {
  const [userInput, setUserInput] = useState("");

  const handleChange = (e: ChangeEvent<HTMLInputElement>) => {
    setUserInput(e.target.value);
  };

  const handleAdd = (e: FormEvent) => {
    e.preventDefault();

    createTodo(userInput);
    setUserInput("");
  };

  return (
    <form onSubmit={handleAdd}>
      <input type="text" onChange={handleChange} value={userInput} />
      <button>Spara</button>
    </form>
  );
};
