// todo-app/src/components/AddTodo.vue
<script setup lang="ts">
import { ref } from "vue";

const userInput = ref("");

const emits = defineEmits<{ (e: "addtodo", text: string): void }>();

const handleSubmit = () => {
  emits("addtodo", userInput.value);

  userInput.value = "";
};
</script>

<template>
  <form @submit.prevent="handleSubmit">
    <input type="text" v-model="userInput" />
    <button>Spara</button>
  </form>
</template>

<style scoped></style>

// 8-react-context/src/components/AddTodo.tsx
import { ChangeEvent, FormEvent, useContext, useState } from "react";
import { TodosContext } from "../contexts/TodosContext";
import { Button } from "./Button";

export const AddTodo = () => {
  const [userInput, setUserInput] = useState("");
  const { add } = useContext(TodosContext);

  const handleSave = (e: FormEvent) => {
    e.preventDefault();

    add(userInput);

    setUserInput("");
  };

  return (
    <form onSubmit={handleSave}>
      <input
        type="text"
        value={userInput}
        onChange={(e: ChangeEvent<HTMLInputElement>) => {
          setUserInput(e.target.value);
        }}
      />
      <Button click={() => {}}>
        <>Spara</>
      </Button>
    </form>
  );
};
