// todo-app/src/components/TodoApp.vue
<script setup lang="ts">
import { ref } from "vue";
import { Todo } from "../models/Todo";
import TodoView from "./TodoView.vue";
import AddTodo from "./AddTodo.vue";

const todos = ref<Todo[]>([]);

const addTodo = (text: string) => {
  todos.value = [...todos.value, new Todo(text, false, new Date().getTime())];
};

const toggleTodo = (id: number) => {
  todos.value = todos.value.map((todo) => {
    if (todo.id === id) {
      return { ...todo, done: !todo.done };
    } else {
      return todo;
    }
  });
};
</script>

<template>
  <AddTodo @addtodo="addTodo"></AddTodo>

  <div>
    <TodoView
      @toggle="toggleTodo"
      v-for="todo in todos"
      :key="todo.id"
      :todo="todo"
    ></TodoView>
  </div>
</template>

<style scoped></style>

// 8-react-context/src/components/TodoApp.tsx
import { useState } from "react";
import { ITodosContext, TodosContext } from "../contexts/TodosContext";
import { Todo } from "../models/Todo";
import { AddTodo } from "./AddTodo";
import { Todos } from "./Todos";

export const TodoApp = () => {
  const [todos, setTodos] = useState<ITodosContext>({
    todos: [new Todo(new Date().getTime(), "Start", false)],
    add: (text: string) => {},
    toggle: (id: number) => {},
  });

  todos.add = (text: string) => {
    setTodos({
      ...todos,
      todos: [...todos.todos, new Todo(new Date().getTime(), text, false)],
    });
  };

  todos.toggle = (id: number) => {
    setTodos({
      ...todos,
      todos: todos.todos.map((todo) => {
        if (todo.id === id) {
          todo.done = !todo.done;
        }
        return todo;
      }),
    });
  };

  return (
    <>
      <TodosContext.Provider value={todos}>
        <AddTodo />
        <Todos />
      </TodosContext.Provider>
    </>
  );
};
