// 1-react-begin/src/App.tsx
import "./App.css";
import { ConditionalRendering } from "./components/ConditionalRendering";
import { HelloWorld } from "./components/HelloWorld";
import { Interpolation } from "./components/Interpolation";
import { Lists } from "./components/Lists";

function App() {
  return (
    <>
      <HelloWorld></HelloWorld>
      <Interpolation></Interpolation>
      <ConditionalRendering></ConditionalRendering>
      <Lists></Lists>
    </>
  );
}

export default App;

// 2-vue-rendering/src/App.vue
<script setup lang="ts">
import Conditional from "./components/Conditional.vue";
import Interpolation from "./components/Interpolation.vue";
import Lists from "./components/Lists.vue";
</script>

<template>
  <Lists></Lists>
  <Conditional></Conditional>
  <Interpolation></Interpolation>
</template>

<style scoped></style>
