// 4-react-props/src/components/AddTodo.tsx
import { ChangeEvent, useState } from "react";

interface IAddTodoProps {
  addTodo: (text: string) => void;
}

export const AddTodo = ({ addTodo }: IAddTodoProps) => {
  const [userInput, setUserInput] = useState("");

  const handleChange = (e: ChangeEvent<HTMLInputElement>) => {
    setUserInput(e.target.value);
  };

  const handleSave = () => {
    addTodo(userInput);
    setUserInput("");
  };

  return (
    <>
      <input value={userInput} onChange={handleChange} />
      <button onClick={handleSave}>Spara</button>
    </>
  );
};

// todo-app/src/components/AddTodo.vue
<script setup lang="ts">
import { ref } from "vue";

const userInput = ref("");

const emits = defineEmits<{ (e: "addtodo", text: string): void }>();

const handleSubmit = () => {
  emits("addtodo", userInput.value);

  userInput.value = "";
};
</script>

<template>
  <form @submit.prevent="handleSubmit">
    <input type="text" v-model="userInput" />
    <button>Spara</button>
  </form>
</template>

<style scoped></style>
