// 4-react-props/src/components/TodoView.tsx
import { IFunctionsProps } from "../models/IFunctionsProps";
import { Todo } from "../models/Todo";
import "./TodoView.css";

interface ITodoViewProps extends IFunctionsProps {
  todo: Todo;
}

export const TodoView = ({ todo, toggle, remove }: ITodoViewProps) => {
  const handleClick = () => {
    toggle(todo.id);
  };

  const handleRemove = () => {
    remove(todo.id);
  };

  return (
    <div>
      <h4 className={todo.done ? "done" : ""}>{todo.text}</h4>
      <button onClick={handleClick}>Toggla</button>
      <button onClick={handleRemove}>Ta bort</button>
    </div>
  );
};

// todo-app/src/components/TodoView.vue
<script setup lang="ts">
import { Todo } from "../models/Todo";

interface ITodoViewProps {
  todo: Todo;
}

const props = defineProps<ITodoViewProps>();

defineEmits<{ (e: "toggle", id: number): void }>();
</script>

<template>
  <div
    @click="() => $emit('toggle', props.todo.id)"
    :class="props.todo.done ? 'done' : ''"
  >
    {{ props.todo.text }}
  </div>
</template>

<style scoped>
.done {
  text-decoration: line-through;
}
</style>
