// 9-react-reducer/src/components/TodoApp.tsx
import { ChangeEvent, FormEvent, useReducer, useState } from "react";
import { ActionType, IAction, TodosReducer } from "../reducers/TodosReducer";

export const TodoApp = () => {
  // const [todos, setTodos] = useState<Todo[]>([]);
  const [todos, dispatch] = useReducer(TodosReducer, []);

  const [userInput, setUserInput] = useState("");

  const handleSubmit = (e: FormEvent) => {
    e.preventDefault();

    // setTodos([...todos, new Todo(new Date().getTime(), userInput, false)]);

    const action: IAction<string> = {
      type: ActionType.ADDED,
      payload: userInput,
    };

    dispatch(action);

    setUserInput("");
  };

  const toggleTodo = (id: number) => {
    // setTodos(
    //   todos.map((todo) => {
    //     if (todo.id === id) todo.done = !todo.done;
    //     return todo;
    //   })
    // );

    const action: IAction<number> = {
      type: ActionType.TOGGLED,
      payload: id,
    };

    dispatch(action);
  };

  return (
    <>
      <form onSubmit={handleSubmit}>
        <input
          type="text"
          value={userInput}
          onChange={(e: ChangeEvent<HTMLInputElement>) => {
            setUserInput(e.target.value);
          }}
        />
        <button>Spara</button>
      </form>
      <section>
        <ul>
          {todos.map((todo) => (
            <li
              key={todo.id}
              onClick={() => toggleTodo(todo.id)}
              className={todo.done ? "done" : ""}
            >
              {todo.text}
            </li>
          ))}
        </ul>
      </section>
    </>
  );
};

// todo-app/src/components/TodoApp.vue
<script setup lang="ts">
import { ref } from "vue";
import { Todo } from "../models/Todo";

const todos = ref<Todo[]>([]);
const userInput = ref("");

const handleInput = (e: Event) => {
  const theInput = e.target as HTMLInputElement;
  userInput.value = theInput.value;
};

const handleSubmit = () => {
  todos.value = [
    ...todos.value,
    new Todo(userInput.value, false, new Date().getTime()),
  ];
};

const toggleTodo = (id: number) => {
  todos.value = todos.value.map((todo) => {
    if (todo.id === id) {
      return { ...todo, done: !todo.done };
    } else {
      return todo;
    }
  });
};
</script>

<template>
  <form @submit.prevent="handleSubmit">
    <input type="text" :value="userInput" @input="handleInput" />
    <button>Spara</button>
  </form>

  <ul>
    <li
      @click="() => toggleTodo(todo.id)"
      v-for="todo in todos"
      :class="todo.done ? 'done' : ''"
      :key="todo.id"
    >
      {{ todo.text }}
    </li>
  </ul>
</template>

<style scoped>
ul {
  list-style: none;
  margin: 0;
  padding: 0;
}
.done {
  text-decoration: line-through;
}
</style>
